{u'search_metadata':
 {u'count': 3,
  u'completed_in': 0.019,
  u'max_id_str': u'721953084469940225',
  u'since_id_str': u'0',
  u'next_results':
  u'?max_id=721953058800996351&q=obama&count=3&include_entities=1',
  u'refresh_url': u'?since_id=721953084469940225&q=obama&include_entities=1',
  u'since_id': 0,
  u'query': u'obama',
  u'max_id': 721953084469940225},
 u'statuses':
 [{u'contributors': None,
   u'truncated': False,
   u'text':
   u'RT @ReaIBeyonce: and here we see the leader of our nation greeting Barack Obama http://t.co/E9aZtubFui',
   u'is_quote_status': False,
   u'in_reply_to_status_id': None,
   u'id': 721953084469940225,
   u'favorite_count': 0,
   u'entities':
   {u'symbols': [],
    u'user_mentions': [{u'id': 3016042992,
                        u'indices': [3, 15],
                        u'id_str': u'3016042992',
                        u'screen_name': u'ReaIBeyonce',
                        u'name': u'Beyonc\xe9'}],
    u'hashtags':
    [],
    u'urls': [],
    u'media':
    [{u'source_user_id': 3016042992,
      u'source_status_id_str': u'581970322661990400',
      u'expanded_url':
      u'http://twitter.com/ReaIBeyonce/status/581970322661990400/photo/1',
      u'display_url': u'pic.twitter.com/E9aZtubFui',
      u'url': u'http://t.co/E9aZtubFui',
      u'media_url_https': u'https://pbs.twimg.com/media/CBOS7M0WUAAgRdJ.jpg',
      u'source_user_id_str': u'3016042992',
      u'source_status_id': 581970322661990400,
      u'id_str': u'581970322611654656',
      u'sizes': {u'small': {u'h': 226,
                            u'resize': u'fit',
                            u'w': 340},
                 u'large': {u'h': 394,
                            u'resize': u'fit',
                            u'w': 592},
                 u'medium': {u'h': 394,
                             u'resize': u'fit',
                             u'w': 592},
                 u'thumb': {u'h': 150,
                            u'resize': u'crop',
                            u'w': 150}},
      u'indices': [80, 102],
      u'type': u'photo',
      u'id': 581970322611654656,
      u'media_url': u'http://pbs.twimg.com/media/CBOS7M0WUAAgRdJ.jpg'}]},
   u'retweeted': False,
   u'coordinates': None,
   u'source':
   u'<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
   u'in_reply_to_screen_name': None,
   u'in_reply_to_user_id': None,
   u'retweet_count': 106,
   u'id_str': u'721953084469940225',
   u'favorited': False,
   u'retweeted_status':
   {u'contributors': None,
    u'truncated': False,
    u'text':
    u'and here we see the leader of our nation greeting Barack Obama http://t.co/E9aZtubFui',
    u'is_quote_status': False,
    u'in_reply_to_status_id': None,
    u'id': 581970322661990400,
    u'favorite_count': 113,
    u'entities':
    {u'symbols': [],
     u'user_mentions': [],
     u'hashtags':
     [],
     u'urls': [],
     u'media':
     [{u'expanded_url':
       u'http://twitter.com/ReaIBeyonce/status/581970322661990400/photo/1',
       u'display_url': u'pic.twitter.com/E9aZtubFui',
       u'url': u'http://t.co/E9aZtubFui',
       u'media_url_https': u'https://pbs.twimg.com/media/CBOS7M0WUAAgRdJ.jpg',
       u'id_str': u'581970322611654656',
       u'sizes': {u'small': {u'h': 226,
                             u'resize': u'fit',
                             u'w': 340},
                  u'large': {u'h': 394,
                             u'resize': u'fit',
                             u'w': 592},
                  u'medium': {u'h': 394,
                              u'resize': u'fit',
                              u'w': 592},
                  u'thumb': {u'h': 150,
                             u'resize': u'crop',
                             u'w': 150}},
       u'indices': [63, 85],
       u'type': u'photo',
       u'id': 581970322611654656,
       u'media_url': u'http://pbs.twimg.com/media/CBOS7M0WUAAgRdJ.jpg'}]},
    u'retweeted': False,
    u'coordinates': None,
    u'source': u'<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
    u'in_reply_to_screen_name': None,
    u'in_reply_to_user_id': None,
    u'retweet_count': 106,
    u'id_str': u'581970322661990400',
    u'favorited': False,
    u'user':
    {u'follow_request_sent': None,
     u'has_extended_profile': False,
     u'profile_use_background_image': False,
     u'default_profile_image': False,
     u'id': 3016042992,
     u'profile_background_image_url_https':
     u'https://abs.twimg.com/images/themes/theme1/bg.png',
     u'verified': False,
     u'profile_text_color': u'000000',
     u'profile_image_url_https':
     u'https://pbs.twimg.com/profile_images/686572397336477696/_e68dmto_normal.jpg',
     u'profile_sidebar_fill_color': u'000000',
     u'entities': {u'url': {u'urls':
                            [{u'url': u'https://t.co/vZE2vfPCgp',
                              u'indices': [0, 23],
                              u'expanded_url': u'http://bit.ly/1QaMYqi',
                              u'display_url': u'bit.ly/1QaMYqi'}]},
                   u'description':
                   {u'urls': [{u'url': u'https://t.co/9oo3n5OiMC',
                               u'indices': [44, 67],
                               u'expanded_url': u'http://bit.ly/1VIEQS2',
                               u'display_url': u'bit.ly/1VIEQS2'}]}},
     u'followers_count': 21281,
     u'profile_sidebar_border_color': u'000000',
     u'id_str': u'3016042992',
     u'profile_background_color': u'000000',
     u'listed_count': 25,
     u'is_translation_enabled': False,
     u'utc_offset': -25200,
     u'statuses_count': 1105,
     u'description':
     u'Full Access to Beyonc\xe9 Videos Here \u27a1\ufe0f \u27a1\ufe0f \u27a1\ufe0f https://t.co/9oo3n5OiMC',
     u'friends_count': 13536,
     u'location': u'Worldwide',
     u'profile_link_color': u'F5ABB5',
     u'profile_image_url':
     u'http://pbs.twimg.com/profile_images/686572397336477696/_e68dmto_normal.jpg',
     u'following': None,
     u'geo_enabled': False,
     u'profile_banner_url':
     u'https://pbs.twimg.com/profile_banners/3016042992/1452527113',
     u'profile_background_image_url':
     u'http://abs.twimg.com/images/themes/theme1/bg.png',
     u'screen_name': u'ReaIBeyonce',
     u'lang': u'en',
     u'profile_background_tile': False,
     u'favourites_count': 20,
     u'name': u'Beyonc\xe9',
     u'notifications': None,
     u'url': u'https://t.co/vZE2vfPCgp',
     u'created_at': u'Tue Feb 10 03:44:52 +0000 2015',
     u'contributors_enabled': False,
     u'time_zone': u'Pacific Time (US & Canada)',
     u'protected': False,
     u'default_profile': False,
     u'is_translator': False},
    u'geo': None,
    u'in_reply_to_user_id_str': None,
    u'possibly_sensitive': False,
    u'lang': u'en',
    u'created_at': u'Sun Mar 29 00:05:12 +0000 2015',
    u'in_reply_to_status_id_str': None,
    u'place': None,
    u'metadata': {u'iso_language_code': u'en',
                  u'result_type': u'recent'}},
   u'user':
   {u'follow_request_sent': None,
    u'has_extended_profile': True,
    u'profile_use_background_image': False,
    u'default_profile_image': False,
    u'id': 1601990376,
    u'profile_background_image_url_https':
    u'https://abs.twimg.com/images/themes/theme1/bg.png',
    u'verified': False,
    u'profile_text_color': u'000000',
    u'profile_image_url_https':
    u'https://pbs.twimg.com/profile_images/721552578878636032/fAt4Aggs_normal.jpg',
    u'profile_sidebar_fill_color': u'000000',
    u'entities': {u'url': {u'urls': [
        {u'url': u'https://t.co/hyv3Nbcs6G',
         u'indices': [0, 23],
         u'expanded_url':
         u'https://twitter.com/ellenpompeo/status/586369859170144256',
         u'display_url': u'twitter.com/ellenpompeo/st\u2026'}
    ]},
                  u'description': {u'urls': []}},
    u'followers_count': 488,
    u'profile_sidebar_border_color': u'000000',
    u'id_str': u'1601990376',
    u'profile_background_color': u'000000',
    u'listed_count': 5,
    u'is_translation_enabled': False,
    u'utc_offset': -25200,
    u'statuses_count': 26618,
    u'description': u'I just really like Beyonc\xe9',
    u'friends_count': 245,
    u'location': u'in my park',
    u'profile_link_color': u'000000',
    u'profile_image_url':
    u'http://pbs.twimg.com/profile_images/721552578878636032/fAt4Aggs_normal.jpg',
    u'following': None,
    u'geo_enabled': True,
    u'profile_banner_url':
    u'https://pbs.twimg.com/profile_banners/1601990376/1460866428',
    u'profile_background_image_url':
    u'http://abs.twimg.com/images/themes/theme1/bg.png',
    u'screen_name': u'sohnidempsey',
    u'lang': u'en',
    u'profile_background_tile': False,
    u'favourites_count': 19864,
    u'name': u'sohni',
    u'notifications': None,
    u'url': u'https://t.co/hyv3Nbcs6G',
    u'created_at': u'Wed Jul 17 22:55:19 +0000 2013',
    u'contributors_enabled': False,
    u'time_zone': u'Tijuana',
    u'protected': False,
    u'default_profile': False,
    u'is_translator': False},
   u'geo': None,
   u'in_reply_to_user_id_str': None,
   u'possibly_sensitive': False,
   u'lang': u'en',
   u'created_at': u'Mon Apr 18 06:46:43 +0000 2016',
   u'in_reply_to_status_id_str': None,
   u'place': None,
   u'metadata': {u'iso_language_code': u'en',
                 u'result_type': u'recent'}},
  {u'contributors': None,
   u'truncated': False,
   u'text':
   u"RT @steve0423: Obama's America!! Number of #IllegalAlien children growing exponentially!!\n#illegalimmigration \n\n#tcot #PJNET https://t.co/x\u2026",
   u'is_quote_status': False,
   u'in_reply_to_status_id': None,
   u'id': 721953077314527233,
   u'favorite_count': 0,
   u'entities':
   {u'symbols': [],
    u'user_mentions': [{u'id': 5644772,
                        u'indices': [3, 13],
                        u'id_str': u'5644772',
                        u'screen_name': u'steve0423',
                        u'name': u'Young Conservative\u2122'}],
    u'hashtags':
    [{u'indices': [43, 56],
      u'text': u'IllegalAlien'}, {u'indices': [90, 109],
                                  u'text': u'illegalimmigration'},
     {u'indices': [112, 117],
      u'text': u'tcot'}, {u'indices': [118, 124],
                          u'text': u'PJNET'}],
    u'urls': [],
    u'media':
    [{u'source_user_id': 5644772,
      u'source_status_id_str': u'721881035001196545',
      u'expanded_url':
      u'http://twitter.com/steve0423/status/721881035001196545/photo/1',
      u'display_url': u'pic.twitter.com/xWVosbFK9V',
      u'url': u'https://t.co/xWVosbFK9V',
      u'media_url_https': u'https://pbs.twimg.com/media/CgSi-IKUAAIdiuN.jpg',
      u'source_user_id_str': u'5644772',
      u'source_status_id': 721881035001196545,
      u'id_str': u'721881028512448514',
      u'sizes': {u'small': {u'h': 495,
                            u'resize': u'fit',
                            u'w': 340},
                 u'large': {u'h': 1024,
                            u'resize': u'fit',
                            u'w': 704},
                 u'medium': {u'h': 873,
                             u'resize': u'fit',
                             u'w': 600},
                 u'thumb': {
                     u'h': 150,
                     u'resize': u'crop',
                     u'w': 150
                 }},
      u'indices': [125, 140],
      u'type': u'photo',
      u'id': 721881028512448514,
      u'media_url': u'http://pbs.twimg.com/media/CgSi-IKUAAIdiuN.jpg'}]},
   u'retweeted': False,
   u'coordinates': None,
   u'source':
   u'<a href="https://mobile.twitter.com" rel="nofollow">Mobile Web (M5)</a>',
   u'in_reply_to_screen_name': None,
   u'in_reply_to_user_id': None,
   u'retweet_count': 59,
   u'id_str': u'721953077314527233',
   u'favorited': False,
   u'retweeted_status':
   {u'contributors': None,
    u'truncated': False,
    u'text':
    u"Obama's America!! Number of #IllegalAlien children growing exponentially!!\n#illegalimmigration \n\n#tcot #PJNET https://t.co/xWVosbFK9V",
    u'is_quote_status': False,
    u'in_reply_to_status_id': None,
    u'id': 721881035001196545,
    u'favorite_count': 37,
    u'entities':
    {u'symbols': [],
     u'user_mentions': [],
     u'hashtags':
     [{u'indices': [28, 41],
       u'text': u'IllegalAlien'}, {u'indices': [75, 94],
                                   u'text': u'illegalimmigration'},
      {u'indices': [97, 102],
       u'text': u'tcot'}, {u'indices': [103, 109],
                           u'text': u'PJNET'}],
     u'urls': [],
     u'media':
     [{u'expanded_url':
       u'http://twitter.com/steve0423/status/721881035001196545/photo/1',
       u'display_url': u'pic.twitter.com/xWVosbFK9V',
       u'url': u'https://t.co/xWVosbFK9V',
       u'media_url_https': u'https://pbs.twimg.com/media/CgSi-IKUAAIdiuN.jpg',
       u'id_str': u'721881028512448514',
       u'sizes': {u'small': {u'h': 495,
                             u'resize': u'fit',
                             u'w': 340},
                  u'large': {u'h': 1024,
                             u'resize': u'fit',
                             u'w': 704},
                  u'medium': {u'h': 873,
                              u'resize': u'fit',
                              u'w': 600},
                  u'thumb': {u'h': 150,
                             u'resize': u'crop',
                             u'w': 150}},
       u'indices': [110, 133],
       u'type': u'photo',
       u'id': 721881028512448514,
       u'media_url': u'http://pbs.twimg.com/media/CgSi-IKUAAIdiuN.jpg'}]},
    u'retweeted': False,
    u'coordinates': None,
    u'source':
    u'<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
    u'in_reply_to_screen_name': None,
    u'in_reply_to_user_id': None,
    u'retweet_count': 59,
    u'id_str': u'721881035001196545',
    u'favorited': False,
    u'user':
    {u'follow_request_sent': None,
     u'has_extended_profile': False,
     u'profile_use_background_image': True,
     u'default_profile_image': False,
     u'id': 5644772,
     u'profile_background_image_url_https':
     u'https://pbs.twimg.com/profile_background_images/378800000162646623/6MgoVKLh.jpeg',
     u'verified': False,
     u'profile_text_color': u'333333',
     u'profile_image_url_https':
     u'https://pbs.twimg.com/profile_images/687278298192293888/CTy2Xz-9_normal.jpg',
     u'profile_sidebar_fill_color': u'FFFFFF',
     u'entities': {u'url':
                   {u'urls':
                    [{u'url': u'https://t.co/lEa4c3b8kU',
                      u'indices': [0, 23],
                      u'expanded_url': u'http://www.youngconservative.net',
                      u'display_url': u'youngconservative.net'}]},
                   u'description': {u'urls': []}},
     u'followers_count': 42872,
     u'profile_sidebar_border_color': u'FFFFFF',
     u'id_str': u'5644772',
     u'profile_background_color': u'FFFFFF',
     u'listed_count': 448,
     u'is_translation_enabled': False,
     u'utc_offset': -14400,
     u'statuses_count': 29631,
     u'description':
     u'Citizen journalist!! Followed by @seanhannity @DailyCaller @AlvedaCKing @DineshDSouza\n@DarrellIssa @DavidLimbaugh @RepJBridenstine\n@heritage\n #TCOT #PJNET',
     u'friends_count': 26211,
     u'location': u'New Jersey',
     u'profile_link_color': u'000000',
     u'profile_image_url':
     u'http://pbs.twimg.com/profile_images/687278298192293888/CTy2Xz-9_normal.jpg',
     u'following': None,
     u'geo_enabled': True,
     u'profile_banner_url':
     u'https://pbs.twimg.com/profile_banners/5644772/1360727804',
     u'profile_background_image_url':
     u'http://pbs.twimg.com/profile_background_images/378800000162646623/6MgoVKLh.jpeg',
     u'screen_name': u'steve0423',
     u'lang': u'en',
     u'profile_background_tile': False,
     u'favourites_count': 5052,
     u'name': u'Young Conservative\u2122',
     u'notifications': None,
     u'url': u'https://t.co/lEa4c3b8kU',
     u'created_at': u'Mon Apr 30 04:39:20 +0000 2007',
     u'contributors_enabled': False,
     u'time_zone': u'Eastern Time (US & Canada)',
     u'protected': False,
     u'default_profile': False,
     u'is_translator': False},
    u'geo': None,
    u'in_reply_to_user_id_str': None,
    u'possibly_sensitive': False,
    u'lang': u'en',
    u'created_at': u'Mon Apr 18 02:00:25 +0000 2016',
    u'in_reply_to_status_id_str': None,
    u'place': None,
    u'metadata': {u'iso_language_code': u'en',
                  u'result_type': u'recent'}},
   u'user':
   {u'follow_request_sent': None,
    u'has_extended_profile': False,
    u'profile_use_background_image': True,
    u'default_profile_image': False,
    u'id': 127693283,
    u'profile_background_image_url_https':
    u'https://pbs.twimg.com/profile_background_images/96311753/Coral.jpg',
    u'verified': False,
    u'profile_text_color': u'333333',
    u'profile_image_url_https':
    u'https://pbs.twimg.com/profile_images/1768950598/Canary_Logo_-_Final_normal.jpg',
    u'profile_sidebar_fill_color': u'FFE699',
    u'entities': {u'description': {u'urls': []}},
    u'followers_count': 14305,
    u'profile_sidebar_border_color': u'C0DEED',
    u'id_str': u'127693283',
    u'profile_background_color': u'C0DEED',
    u'listed_count': 698,
    u'is_translation_enabled': False,
    u'utc_offset': None,
    u'statuses_count': 310233,
    u'description':
    u'Concerned citizens against #GMOs/#GMO. We stand for #freedom. Against #tyranny. Constitutionalists. NWO big picture. \xa9RSS Feeds',
    u'friends_count': 15733,
    u'location': u'The Surveillance State U.S.A.',
    u'profile_link_color': u'0084B4',
    u'profile_image_url':
    u'http://pbs.twimg.com/profile_images/1768950598/Canary_Logo_-_Final_normal.jpg',
    u'following': None,
    u'geo_enabled': False,
    u'profile_background_image_url':
    u'http://pbs.twimg.com/profile_background_images/96311753/Coral.jpg',
    u'screen_name': u'CANARYorg',
    u'lang': u'en',
    u'profile_background_tile': False,
    u'favourites_count': 4656,
    u'name': u'Canary Organization',
    u'notifications': None,
    u'url': None,
    u'created_at': u'Tue Mar 30 00:12:41 +0000 2010',
    u'contributors_enabled': False,
    u'time_zone': None,
    u'protected': False,
    u'default_profile': False,
    u'is_translator': False},
   u'geo': None,
   u'in_reply_to_user_id_str': None,
   u'possibly_sensitive': False,
   u'lang': u'en',
   u'created_at': u'Mon Apr 18 06:46:41 +0000 2016',
   u'in_reply_to_status_id_str': None,
   u'place': None,
   u'metadata': {u'iso_language_code': u'en',
                 u'result_type': u'recent'}},
  {u'contributors': None,
   u'truncated': False,
   u'text':
   u'@HectoRodriguez NO LO CREO. Y NO ES OBAMA. SOMOS LOS VENEZOLANOS LOS QUE NO LO PERMITIREMOS. YA BASTA! VAYANSE CARAJO!',
   u'is_quote_status': False,
   u'in_reply_to_status_id': 721878992379371521,
   u'id': 721953058800996352,
   u'favorite_count': 0,
   u'entities': {u'symbols': [],
                 u'user_mentions': [{u'id': 73672296,
                                     u'indices': [0, 15],
                                     u'id_str': u'73672296',
                                     u'screen_name': u'HectoRodriguez',
                                     u'name': u'H\xe9ctor Rodr\xedguez C.'}],
                 u'hashtags': [],
                 u'urls': []},
   u'retweeted': False,
   u'coordinates': None,
   u'source':
   u'<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
   u'in_reply_to_screen_name': u'HectoRodriguez',
   u'in_reply_to_user_id': 73672296,
   u'retweet_count': 0,
   u'id_str': u'721953058800996352',
   u'favorited': False,
   u'user':
   {u'follow_request_sent': None,
    u'has_extended_profile': True,
    u'profile_use_background_image': True,
    u'default_profile_image': False,
    u'id': 1395569070,
    u'profile_background_image_url_https':
    u'https://pbs.twimg.com/profile_background_images/451951593575813120/G_CqoU8X.jpeg',
    u'verified': False,
    u'profile_text_color': u'3C3940',
    u'profile_image_url_https':
    u'https://pbs.twimg.com/profile_images/605224537253380096/sPvtBOpE_normal.jpg',
    u'profile_sidebar_fill_color': u'95E8EC',
    u'entities': {u'description': {u'urls': []}},
    u'followers_count': 1256,
    u'profile_sidebar_border_color': u'FFFFFF',
    u'id_str': u'1395569070',
    u'profile_background_color': u'0099B9',
    u'listed_count': 14,
    u'is_translation_enabled': False,
    u'utc_offset': 10800,
    u'statuses_count': 42333,
    u'description': u'Mas que dem\xf3crata, soy REPUBLICANA',
    u'friends_count': 658,
    u'location': u'',
    u'profile_link_color': u'9266CC',
    u'profile_image_url':
    u'http://pbs.twimg.com/profile_images/605224537253380096/sPvtBOpE_normal.jpg',
    u'following': None,
    u'geo_enabled': False,
    u'profile_banner_url':
    u'https://pbs.twimg.com/profile_banners/1395569070/1440185831',
    u'profile_background_image_url':
    u'http://pbs.twimg.com/profile_background_images/451951593575813120/G_CqoU8X.jpeg',
    u'screen_name': u'CLARAROSApp',
    u'lang': u'es',
    u'profile_background_tile': False,
    u'favourites_count': 2702,
    u'name': u'CLARAROSA',
    u'notifications': None,
    u'url': None,
    u'created_at': u'Wed May 01 21:11:45 +0000 2013',
    u'contributors_enabled': False,
    u'time_zone': u'Athens',
    u'protected': False,
    u'default_profile': False,
    u'is_translator': False},
   u'geo': None,
   u'in_reply_to_user_id_str': u'73672296',
   u'lang': u'es',
   u'created_at': u'Mon Apr 18 06:46:37 +0000 2016',
   u'in_reply_to_status_id_str': u'721878992379371521',
   u'place': None,
   u'metadata': {u'iso_language_code': u'es',
                 u'result_type': u'recent'}}]}
